export type TeamInfo = {
  teamId: string;
  lang: "ZH" | "EN";
  region: string;
  company: string;
  contact: { name: string; occupation: string; avatarUrl: string };
  logoUrl: string;
  established: string;
  fundingAmount: string;
  annualRevenue: string;
  currentFundingRound: string;
  currentFundingAmount: string;
  postMoneyValuation: string;
  project: string;
  mainInvester: string;
  highlights: string[];
  coreTech: string;
  coreTechKeywords: string[];
  targetMarket: string;
  coreProducts: { name: string; type: string; progress: number; countries: string }[];
  milestones: string[];
  error?: string;
};
